[2023-02-27T16:05:20.020+0000] {processor.py:153} INFO - Started process (PID=224) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:05:20.022+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:05:20.023+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:05:20.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:05:20.081+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:05:20.074+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:05:20.085+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:05:20.108+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.092 seconds
[2023-02-27T16:05:50.446+0000] {processor.py:153} INFO - Started process (PID=234) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:05:50.448+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:05:50.448+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:05:50.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:05:50.477+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:05:50.472+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:05:50.479+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:05:50.500+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.056 seconds
[2023-02-27T16:06:20.849+0000] {processor.py:153} INFO - Started process (PID=244) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:06:20.850+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:06:20.852+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:06:20.852+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:06:20.897+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:06:20.886+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:06:20.901+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:06:20.929+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.085 seconds
[2023-02-27T16:06:51.244+0000] {processor.py:153} INFO - Started process (PID=254) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:06:51.245+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:06:51.246+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:06:51.246+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:06:51.286+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:06:51.279+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:06:51.288+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:06:51.312+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.070 seconds
[2023-02-27T16:07:21.663+0000] {processor.py:153} INFO - Started process (PID=264) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:07:21.665+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:07:21.666+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:07:21.666+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:07:21.715+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:07:21.706+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:07:21.718+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:07:21.744+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.083 seconds
[2023-02-27T16:07:52.094+0000] {processor.py:153} INFO - Started process (PID=274) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:07:52.095+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:07:52.097+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:07:52.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:07:52.135+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:07:52.124+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:07:52.138+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:07:52.164+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.074 seconds
[2023-02-27T16:08:22.555+0000] {processor.py:153} INFO - Started process (PID=284) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:08:22.556+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:08:22.557+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:08:22.557+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:08:22.608+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:08:22.599+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:08:22.611+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:08:22.634+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.082 seconds
[2023-02-27T16:08:53.061+0000] {processor.py:153} INFO - Started process (PID=294) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:08:53.063+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:08:53.064+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:08:53.064+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:08:53.113+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:08:53.105+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:08:53.116+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:08:53.142+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.085 seconds
[2023-02-27T16:09:23.514+0000] {processor.py:153} INFO - Started process (PID=304) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:09:23.516+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:09:23.517+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:09:23.517+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:09:23.572+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:09:23.561+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:09:23.576+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:09:23.606+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.096 seconds
[2023-02-27T16:09:54.011+0000] {processor.py:153} INFO - Started process (PID=314) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:09:54.012+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:09:54.013+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:09:54.013+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:09:54.065+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:09:54.055+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:09:54.069+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:09:54.091+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.083 seconds
[2023-02-27T16:10:24.655+0000] {processor.py:153} INFO - Started process (PID=324) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:10:24.656+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:10:24.657+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:10:24.657+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:10:24.700+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:10:24.693+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:10:24.704+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:10:24.727+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.076 seconds
[2023-02-27T16:10:55.165+0000] {processor.py:153} INFO - Started process (PID=334) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:10:55.166+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:10:55.168+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:10:55.168+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:10:55.204+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:10:55.198+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:10:55.206+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:10:55.235+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.072 seconds
[2023-02-27T16:11:25.693+0000] {processor.py:153} INFO - Started process (PID=344) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:11:25.694+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:11:25.696+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:11:25.695+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:11:25.747+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:11:25.738+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:11:25.751+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:11:25.781+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.092 seconds
[2023-02-27T16:11:56.201+0000] {processor.py:153} INFO - Started process (PID=354) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:11:56.202+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:11:56.203+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:11:56.203+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:11:56.246+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:11:56.236+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:11:56.249+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:11:56.280+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.082 seconds
[2023-02-27T16:12:26.712+0000] {processor.py:153} INFO - Started process (PID=364) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:12:26.714+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:12:26.715+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:12:26.715+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:12:26.770+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:12:26.760+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:12:26.774+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:12:26.802+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.093 seconds
[2023-02-27T16:12:57.206+0000] {processor.py:153} INFO - Started process (PID=374) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:12:57.208+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:12:57.210+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:12:57.209+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:12:57.263+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:12:57.252+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:12:57.266+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:12:57.297+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.094 seconds
[2023-02-27T16:13:27.740+0000] {processor.py:153} INFO - Started process (PID=384) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:13:27.741+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:13:27.743+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:13:27.742+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:13:27.797+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:13:27.784+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:13:27.801+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:13:27.828+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.090 seconds
[2023-02-27T16:13:58.181+0000] {processor.py:153} INFO - Started process (PID=394) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:13:58.182+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:13:58.183+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:13:58.183+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:13:58.210+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:13:58.205+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:13:58.212+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:13:58.236+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.058 seconds
[2023-02-27T16:14:28.590+0000] {processor.py:153} INFO - Started process (PID=404) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:14:28.591+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:14:28.593+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:14:28.592+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:14:28.629+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:14:28.623+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:14:28.631+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:14:28.653+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.065 seconds
[2023-02-27T16:14:59.062+0000] {processor.py:153} INFO - Started process (PID=414) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:14:59.063+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:14:59.065+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:14:59.065+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:14:59.098+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:14:59.093+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:14:59.099+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:14:59.123+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.064 seconds
[2023-02-27T16:15:29.552+0000] {processor.py:153} INFO - Started process (PID=424) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:15:29.554+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:15:29.556+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:15:29.556+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:15:29.618+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:15:29.606+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:15:29.622+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:15:29.651+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.104 seconds
[2023-02-27T16:16:00.087+0000] {processor.py:153} INFO - Started process (PID=434) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:16:00.089+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:16:00.090+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:16:00.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:16:00.128+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:16:00.121+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:16:00.131+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:16:00.172+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.087 seconds
[2023-02-27T16:16:30.617+0000] {processor.py:153} INFO - Started process (PID=444) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:16:30.618+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:16:30.619+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:16:30.619+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:16:30.659+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:16:30.651+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:16:30.662+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:16:30.691+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.078 seconds
[2023-02-27T16:17:01.111+0000] {processor.py:153} INFO - Started process (PID=454) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:17:01.112+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:17:01.114+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:17:01.114+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:17:01.171+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:17:01.161+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:17:01.174+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:17:01.196+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.088 seconds
[2023-02-27T16:17:31.580+0000] {processor.py:153} INFO - Started process (PID=464) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:17:31.581+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:17:31.583+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:17:31.583+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:17:31.622+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:17:31.614+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:17:31.624+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:17:31.646+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.068 seconds
[2023-02-27T16:18:02.052+0000] {processor.py:153} INFO - Started process (PID=474) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:18:02.054+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:18:02.055+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:18:02.055+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:18:02.088+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:18:02.080+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:18:02.091+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:18:02.118+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.069 seconds
[2023-02-27T16:18:32.516+0000] {processor.py:153} INFO - Started process (PID=484) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:18:32.518+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:18:32.519+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:18:32.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:18:32.572+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:18:32.564+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:18:32.577+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:18:32.597+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.083 seconds
[2023-02-27T16:19:03.040+0000] {processor.py:153} INFO - Started process (PID=494) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:19:03.041+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:19:03.042+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:19:03.042+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:19:03.071+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:19:03.066+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:19:03.073+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:19:03.101+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.064 seconds
[2023-02-27T16:19:33.575+0000] {processor.py:153} INFO - Started process (PID=504) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:19:33.577+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:19:33.579+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:19:33.579+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:19:33.642+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:19:33.631+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:19:33.645+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:19:33.667+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.097 seconds
[2023-02-27T16:20:04.102+0000] {processor.py:153} INFO - Started process (PID=514) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:20:04.103+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:20:04.105+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:20:04.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:20:04.143+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:20:04.136+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:20:04.145+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:20:04.173+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.074 seconds
[2023-02-27T16:20:34.590+0000] {processor.py:153} INFO - Started process (PID=524) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:20:34.592+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:20:34.594+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:20:34.594+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:20:34.652+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:20:34.641+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:20:34.656+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:20:34.686+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.101 seconds
[2023-02-27T16:21:05.099+0000] {processor.py:153} INFO - Started process (PID=534) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:21:05.100+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:21:05.102+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:21:05.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:21:05.149+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:21:05.143+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:21:05.151+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:21:05.176+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.080 seconds
[2023-02-27T16:21:35.568+0000] {processor.py:153} INFO - Started process (PID=544) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:21:35.570+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:21:35.571+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:21:35.571+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:21:35.610+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:21:35.603+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:21:35.613+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:21:35.656+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.089 seconds
[2023-02-27T16:22:06.102+0000] {processor.py:153} INFO - Started process (PID=554) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:22:06.104+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:22:06.105+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:22:06.105+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:22:06.150+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:22:06.140+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:22:06.153+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:22:06.179+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.079 seconds
[2023-02-27T16:22:36.599+0000] {processor.py:153} INFO - Started process (PID=564) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:22:36.601+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:22:36.602+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:22:36.602+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:22:36.652+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:22:36.642+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:22:36.655+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:22:36.677+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.080 seconds
[2023-02-27T16:23:07.099+0000] {processor.py:153} INFO - Started process (PID=574) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:07.101+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:23:07.103+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:07.102+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:07.150+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:07.141+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:23:07.152+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:07.174+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.077 seconds
[2023-02-27T16:23:37.540+0000] {processor.py:153} INFO - Started process (PID=584) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:37.542+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:23:37.543+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:37.543+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:37.595+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:37.585+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:23:37.598+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:37.631+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.094 seconds
[2023-02-27T16:23:52.824+0000] {processor.py:153} INFO - Started process (PID=594) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:52.826+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:23:52.827+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:52.827+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:52.911+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:52.903+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:23:52.914+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:52.936+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.115 seconds
[2023-02-27T16:23:53.949+0000] {processor.py:153} INFO - Started process (PID=599) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:53.951+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:23:53.952+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:53.952+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:54.050+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:23:54.040+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:23:54.054+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:23:54.083+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.137 seconds
[2023-02-27T16:24:24.433+0000] {processor.py:153} INFO - Started process (PID=609) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:24.434+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:24:24.435+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:24:24.435+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:24.475+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:24:24.469+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:24:24.478+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:24.497+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.067 seconds
[2023-02-27T16:24:25.492+0000] {processor.py:153} INFO - Started process (PID=614) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:25.493+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:24:25.495+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:24:25.494+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:25.556+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:24:25.551+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:24:25.559+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:25.585+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.097 seconds
[2023-02-27T16:24:55.944+0000] {processor.py:153} INFO - Started process (PID=624) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:55.946+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:24:55.947+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:24:55.947+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:55.997+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:24:55.987+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:24:55.999+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:24:56.022+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.081 seconds
[2023-02-27T16:25:26.434+0000] {processor.py:153} INFO - Started process (PID=634) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:25:26.436+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:25:26.437+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:25:26.437+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:25:26.491+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:25:26.481+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:25:26.494+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:25:26.525+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.094 seconds
[2023-02-27T16:25:56.936+0000] {processor.py:153} INFO - Started process (PID=644) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:25:56.938+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:25:56.939+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:25:56.939+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:25:56.979+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:25:56.972+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 2, in <module>
    import networkx as nx
ModuleNotFoundError: No module named 'networkx'
[2023-02-27T16:25:56.982+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:25:57.012+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.081 seconds
[2023-02-27T16:26:03.082+0000] {processor.py:153} INFO - Started process (PID=649) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:03.083+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:26:03.085+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:26:03.084+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:03.155+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:26:03.150+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 3, in <module>
    from airflow.operators import BashOperator, SubDagOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2023-02-27T16:26:03.157+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:03.179+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.100 seconds
[2023-02-27T16:26:13.221+0000] {processor.py:153} INFO - Started process (PID=654) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:13.222+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:26:13.223+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:26:13.223+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:13.293+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:26:13.287+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2023-02-27T16:26:13.295+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:13.317+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.099 seconds
[2023-02-27T16:26:43.741+0000] {processor.py:153} INFO - Started process (PID=664) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:43.743+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:26:43.744+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:26:43.744+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:43.786+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:26:43.781+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2023-02-27T16:26:43.788+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:26:43.808+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.070 seconds
[2023-02-27T16:27:14.168+0000] {processor.py:153} INFO - Started process (PID=674) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:27:14.170+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:27:14.171+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:27:14.170+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:27:14.215+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:27:14.207+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2023-02-27T16:27:14.219+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:27:14.246+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.081 seconds
[2023-02-27T16:27:44.585+0000] {processor.py:153} INFO - Started process (PID=684) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:27:44.586+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:27:44.587+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:27:44.587+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:27:44.633+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:27:44.625+0000] {dagbag.py:343} ERROR - Failed to import: /opt/airflow/dags/dbt_example.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 339, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/dbt_example.py", line 3, in <module>
    from airflow.operators import BashOperator
ImportError: cannot import name 'BashOperator' from 'airflow.operators' (/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/__init__.py)
[2023-02-27T16:27:44.637+0000] {processor.py:755} WARNING - No viable dags retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:27:44.659+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.077 seconds
[2023-02-27T16:28:11.986+0000] {processor.py:153} INFO - Started process (PID=694) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:11.987+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:28:11.988+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:11.988+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:12.062+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:12.177+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:12.176+0000] {manager.py:504} INFO - Created Permission View: can delete on DAG:dbt
[2023-02-27T16:28:12.188+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:12.188+0000] {manager.py:504} INFO - Created Permission View: can edit on DAG:dbt
[2023-02-27T16:28:12.196+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:12.196+0000] {manager.py:504} INFO - Created Permission View: can read on DAG:dbt
[2023-02-27T16:28:12.197+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:12.196+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:28:12.209+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:12.208+0000] {dag.py:2711} INFO - Creating ORM DAG for dbt
[2023-02-27T16:28:12.221+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:12.221+0000] {dag.py:3441} INFO - Setting next_dagrun for dbt to 2016-01-01T00:00:00+00:00, run_after=2016-01-01T01:00:00+00:00
[2023-02-27T16:28:12.252+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.270 seconds
[2023-02-27T16:28:28.528+0000] {processor.py:153} INFO - Started process (PID=704) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:28.530+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:28:28.531+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:28.531+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:28.612+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:28.663+0000] {processor.py:376} INFO - Running SLA Checks for dbt
[2023-02-27T16:28:28.703+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-02-27T16:28:28.728+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:28.728+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:28:28.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.266 seconds
[2023-02-27T16:28:59.225+0000] {processor.py:153} INFO - Started process (PID=716) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:59.228+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:28:59.230+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:59.230+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:59.293+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:59.337+0000] {processor.py:376} INFO - Running SLA Checks for dbt
[2023-02-27T16:28:59.368+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-02-27T16:28:59.408+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:59.408+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:28:59.451+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:59.451+0000] {dag.py:3441} INFO - Setting next_dagrun for dbt to 2016-01-01T01:00:00+00:00, run_after=2016-01-01T02:00:00+00:00
[2023-02-27T16:28:59.488+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.271 seconds
[2023-02-27T16:28:59.774+0000] {processor.py:153} INFO - Started process (PID=721) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:59.775+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:28:59.777+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:59.777+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:59.823+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:28:59.856+0000] {processor.py:376} INFO - Running SLA Checks for dbt
[2023-02-27T16:28:59.890+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-02-27T16:28:59.935+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:28:59.935+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:28:59.993+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.222 seconds
[2023-02-27T16:29:30.523+0000] {processor.py:153} INFO - Started process (PID=741) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:29:30.525+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:29:30.526+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:29:30.526+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:29:30.569+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:29:30.588+0000] {processor.py:376} INFO - Running SLA Checks for dbt
[2023-02-27T16:29:30.605+0000] {logging_mixin.py:137} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/sqlalchemy.py:124 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2023-02-27T16:29:30.629+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:29:30.629+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:29:30.676+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.156 seconds
[2023-02-27T16:30:00.839+0000] {processor.py:153} INFO - Started process (PID=751) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:30:00.841+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:30:00.842+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:30:00.842+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:30:00.879+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:30:00.902+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:30:00.902+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:30:00.942+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.106 seconds
[2023-02-27T16:30:31.289+0000] {processor.py:153} INFO - Started process (PID=761) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:30:31.290+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:30:31.292+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:30:31.292+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:30:31.333+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:30:31.360+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:30:31.360+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:30:31.384+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:30:31.384+0000] {dag.py:3441} INFO - Setting next_dagrun for dbt to 2016-01-01T11:00:00+00:00, run_after=2016-01-01T12:00:00+00:00
[2023-02-27T16:30:31.406+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.120 seconds
[2023-02-27T16:31:01.749+0000] {processor.py:153} INFO - Started process (PID=771) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:31:01.751+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:31:01.752+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:31:01.752+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:31:01.789+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:31:01.813+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:31:01.812+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:31:01.837+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:31:01.837+0000] {dag.py:3441} INFO - Setting next_dagrun for dbt to 2016-01-01T11:00:00+00:00, run_after=2016-01-01T12:00:00+00:00
[2023-02-27T16:31:01.859+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.113 seconds
[2023-02-27T16:31:32.198+0000] {processor.py:153} INFO - Started process (PID=781) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:31:32.199+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:31:32.200+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:31:32.200+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:31:32.239+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:31:32.266+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:31:32.266+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:31:32.290+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:31:32.290+0000] {dag.py:3441} INFO - Setting next_dagrun for dbt to 2016-01-01T11:00:00+00:00, run_after=2016-01-01T12:00:00+00:00
[2023-02-27T16:31:32.314+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.119 seconds
[2023-02-27T16:32:02.671+0000] {processor.py:153} INFO - Started process (PID=791) to work on /opt/airflow/dags/dbt_example.py
[2023-02-27T16:32:02.672+0000] {processor.py:743} INFO - Processing file /opt/airflow/dags/dbt_example.py for tasks to queue
[2023-02-27T16:32:02.673+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:32:02.673+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:32:02.710+0000] {processor.py:753} INFO - DAG(s) dict_keys(['dbt']) retrieved from /opt/airflow/dags/dbt_example.py
[2023-02-27T16:32:02.739+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:32:02.739+0000] {dag.py:2690} INFO - Sync 1 DAGs
[2023-02-27T16:32:02.762+0000] {logging_mixin.py:137} INFO - [2023-02-27T16:32:02.762+0000] {dag.py:3441} INFO - Setting next_dagrun for dbt to 2016-01-01T11:00:00+00:00, run_after=2016-01-01T12:00:00+00:00
[2023-02-27T16:32:02.791+0000] {processor.py:175} INFO - Processing /opt/airflow/dags/dbt_example.py took 0.123 seconds
